export const metadata = {
    title: "Portfolio",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return (
      <div style={{ scrollBehavior: "smooth" }} className="antialiased flex flex-col items-start bg-background w-full px-2 sm:px-8  md:mt-10">
        <div className="w-full mx-auto">
          {children}
        </div>
      </div>
    );
  }
  