import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Aniket's Portfolio",
  description: "Generated by create next app",
};

const navItems = [
  {
    name: "Home",
    link: '/',
    // icon: <IconHome className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "projects",
    link: '/projects',
    // icon: <IconUser className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "blogs",
    link: "/blogs", 
    // icon: (
    //   // <IconMessage className="h-4 w-4 text-neutral-500 dark:text-white" />
    // ),
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth flex flex-col items-start text-white bg-[#010101] w-full px-2 sm:px-8 lg:px-[19%]`}
      >
        <NavBar ></NavBar>
        {children}
      </body>
    </html>
  );
}
