export const ProjectsData = [
    {
      id: 1,
      Heading: 'Multi-User Chat App',
      Description: 'A real-time chat application based on WebSockets, built using React, Node.js, Express, and MongoDB.',
      isOnGithub: true,
      SourceCode: 'https://github.com/example1',
      isLive: true,
      LiveLink: 'http://example1.com',
      isDetailed: true,
      Details: {
        TechStack: ['React', 'Node.js', 'Express', 'MongoDB', 'WebSocket'],
        Features: [
          'Real-time messaging',
          'User authentication and chat rooms',
          'Responsive design for mobile and desktop',
        ],
        Challenges: [
          'Handling multiple concurrent users efficiently',
          'Implementing WebSocket communication securely',
        ],
      },
    },
    {
      id: 2,
      Heading: 'Portfolio Website',
      Description: 'A personal portfolio website showcasing projects and blogs, built with HTML, CSS, and JavaScript.',
      isOnGithub: true,
      SourceCode: 'https://github.com/example2',
      isLive: true,
      LiveLink: 'http://example2.com',
      isDetailed: false,
      Details: {
        TechStack: ['HTML', 'CSS', 'JavaScript'],
        Features: [
          'Interactive animations and transitions',
          'Custom blog section with markdown support',
          'Responsive design for various screen sizes',
        ],
        Challenges: ['Optimizing animations for performance on older devices'],
      },
    },
    {
      id: 3,
      Heading: 'E-Commerce Store',
      Description: 'A fully functional e-commerce platform with product search, cart, and payment gateway integration, built with MERN stack.',
      isOnGithub: true,
      SourceCode: 'https://github.com/example3',
      isLive: true,
      LiveLink: 'http://example3.com',
      isDetailed: true,
      Details: {
        TechStack: ['MongoDB', 'Express', 'React', 'Node.js', 'Stripe API'],
        Features: [
          'Product search and filter functionality',
          'User authentication and order history',
          'Secure payment gateway integration',
        ],
        Challenges: [
          'Implementing payment gateway securely',
          'Managing large datasets for products efficiently',
        ],
      },
    },
    {
      id: 4,
      Heading: 'Weather App',
      Description: 'A weather forecasting app using OpenWeather API, displaying real-time data for various cities.',
      isOnGithub: true,
      SourceCode: 'https://github.com/example4',
      isLive: true,
      LiveLink: 'http://example4.com',
      isDetailed: false,
      Details: {
        TechStack: ['React', 'OpenWeather API', 'CSS'],
        Features: [
          'Real-time weather updates',
          'Search functionality for cities',
          'Custom weather icons and animations',
        ],
        Challenges: ['Handling API rate limits for frequent requests'],
      },
    },
    {
      id: 5,
      Heading: 'Task Management Tool',
      Description: 'A task management app with CRUD operations, built using React and Firebase for backend and authentication.',
      isOnGithub: true,
      SourceCode: 'https://github.com/example5',
      isLive: true,
      LiveLink: 'http://example5.com',
      isDetailed: true,
      Details: {
        TechStack: ['React', 'Firebase', 'Material-UI'],
        Features: [
          'Add, edit, and delete tasks',
          'User-specific task lists with authentication',
          'Drag-and-drop task organization',
        ],
        Challenges: ['Ensuring real-time updates across all users'],
      },
    },
    {
      id: 6,
      Heading: 'Blogging Platform',
      Description: 'A blogging platform allowing users to create, edit, and delete posts, with markdown support and user authentication.',
      isOnGithub: true,
      SourceCode: 'https://github.com/example6',
      isLive: true,
      LiveLink: 'http://example6.com',
      isDetailed: true,
      Details: {
        TechStack: ['Node.js', 'Express', 'React', 'MongoDB'],
        Features: [
          'Markdown editor for writing posts',
          'User profiles and authentication',
          'Commenting system with spam protection',
        ],
        Challenges: ['Implementing an efficient markdown parser'],
      },
    },

    {
        id: 7,
        Heading: 'Fitness Tracker App',
        Description: 'A mobile-friendly fitness tracking app with user-specific goals and progress tracking, built using React Native and Firebase.',
        isOnGithub: true,
        SourceCode: 'https://github.com/example7',
        isLive: true,
        LiveLink: 'http://example7.com',
        isDetailed: true,
        Details: {
          TechStack: ['React Native', 'Firebase', 'Redux'],
          Features: [
            'Track workouts and calorie intake',
            'Progress charts and analytics',
            'User authentication and goal setting',
          ],
          Challenges: [
            'Managing real-time data sync across devices',
            'Optimizing app performance on older phones',
          ],
        },
      },
      {
        id: 8,
        Heading: 'Recipe Sharing Platform',
        Description: 'A platform for users to share and discover recipes, built with the Django framework and PostgreSQL.',
        isOnGithub: true,
        SourceCode: 'https://github.com/example8',
        isLive: true,
        LiveLink: 'http://example8.com',
        isDetailed: true,
        Details: {
          TechStack: ['Django', 'PostgreSQL', 'Bootstrap'],
          Features: [
            'Search and filter recipes by ingredients and cuisine',
            'User profiles with saved recipes',
            'Recipe rating and commenting',
          ],
          Challenges: ['Ensuring secure user data handling'],
        },
      },
      {
        id: 9,
        Heading: 'Stock Market Dashboard',
        Description: 'A stock market tracking and visualization dashboard using React and Chart.js.',
        isOnGithub: true,
        SourceCode: 'https://github.com/example9',
        isLive: true,
        LiveLink: 'http://example9.com',
        isDetailed: false,
        Details: {
          TechStack: ['React', 'Chart.js', 'Axios'],
          Features: [
            'Real-time stock price updates',
            'Interactive charts for performance analysis',
            'Customizable watchlists',
          ],
          Challenges: ['Handling high-frequency API requests efficiently'],
        },
      },
      {
        id: 10,
        Heading: 'Language Learning App',
        Description: 'An app to help users learn new languages with flashcards and quizzes, built with Flutter and Firebase.',
        isOnGithub: true,
        SourceCode: 'https://github.com/example10',
        isLive: true,
        LiveLink: 'http://example10.com',
        isDetailed: true,
        Details: {
          TechStack: ['Flutter', 'Firebase', 'SQLite'],
          Features: [
            'Customizable flashcard sets',
            'Timed quizzes and progress tracking',
            'Offline access for learning on the go',
          ],
          Challenges: ['Implementing offline mode with local data sync'],
        },
      },
      {
        id: 11,
        Heading: 'Expense Tracker',
        Description: 'A web application to track daily expenses and generate monthly reports, built with Angular and Firebase.',
        isOnGithub: true,
        SourceCode: 'https://github.com/example11',
        isLive: true,
        LiveLink: 'http://example11.com',
        isDetailed: false,
        Details: {
          TechStack: ['Angular', 'Firebase', 'Chart.js'],
          Features: [
            'Expense categorization and filtering',
            'Monthly and yearly spending reports',
            'Real-time data sync across devices',
          ],
          Challenges: ['Designing an intuitive user interface for data input'],
        },
      },
      {
        id: 12,
        Heading: 'Travel Planning App',
        Description: 'An app to plan and organize trips, with itinerary sharing and travel suggestions, built with Vue.js and Firebase.',
        isOnGithub: true,
        SourceCode: 'https://github.com/example12',
        isLive: true,
        LiveLink: 'http://example12.com',
        isDetailed: true,
        Details: {
          TechStack: ['Vue.js', 'Firebase', 'Tailwind CSS'],
          Features: [
            'Collaborative itinerary planning',
            'Travel budget management',
            'Recommended destinations based on user preferences',
          ],
          Challenges: ['Implementing real-time collaboration features'],
        },
      },
  ];
  